### ISSUE TITLE
Exception on bungeecord

### ISSUE THREAD

**Issue by Fejm** [libraryaddict/LibsDisguises#252] opened 2017-07-30 11:43 UTC
Hi!

I have custom NPC spawned by packets on my KitPVP server. Player must right-click on them to get kit.

After installing LibsDisguises any click on my custom NPC  is causing disconnect if server is behind bungeecord.

https://pastebin.com/UbtvTUv3

Latest Spigot, BungeeCord and ProtocolLib

**Comment by Fejm** [comment] 2017-07-30 11:49
In order to reproduce: set negative entity ID when spawning.

**Comment by libraryaddict** [comment] 2017-07-30 19:43
Can you test on latest the latest dev build

**Comment by Fejm** [comment] 2017-07-30 20:15
Still the same. 

You can reproduce this issue using this code: https://pastebin.com/S8EgBGWs (don't hate, created ASAP)

Plugin will work fine without LibDisguises.

**Comment by libraryaddict** [comment] 2017-07-30 20:41
Are you sure you're using the latest dev build?
Because the last commit turns the negative self disguise ID into a positive.

**Comment by Fejm** [comment] 2017-07-30 20:49
I think you missunderstand me. I'm using negative ID but for custom NPC spawned directly by my code not by LibDisguises.

LibDisguises don't know anything about this "fake entity". After sending packet for ex. WrapperPlayServerAnimation with negative ID it's disconneting client.

After some research i figured that bungee disconnects client becouse of wrong / bad packet ID. It cant read packet ID for some reason.

Sorry for my poor English.:C

**Comment by Fejm** [comment] 2017-07-31 02:51
Okey, it seems that is ProtocolLib bug..

**Comment by libraryaddict** [comment] 2017-08-06 04:17
Duplicate of #245

**Closed by libraryaddict** 2017-08-06 04:17 UTC
