### ISSUE TITLE
Cannot modify the bounding box of a disguise which is not TargetType.SHOW_TO_EVERYONE_BUT_THESE_PLAYERS

### ISSUE THREAD

**Issue by totemo** [libraryaddict/LibsDisguises#525] opened 2020-12-04 04:49 UTC
I'm seeing this exception in the latest snapshot (build #809) and also the latest premium release downloaded from the spigot resource page. Running on PaperSpigot git-Paper-249 (MC: 1.16.3).

All disguises are created with `DisguiseAPI.disguiseToAll(Entity,Disguise)` and are mobs disguised as players. I was seeing the same error much more frequently when only sending disguises to selected players, and basically just gave up on that. The same code (sending disguises to selected players) used to work perfectly in the previous major release of Minecraft, and if I recall correctly, the release before that. The new requirement on the bounding box in LibsDisguises code has broken it.

The exceptions seen below seem to be occurring when the chunk containing a disguised mob is unloaded and are entirely in server code and LibsDisguises.

Oh and I guess this explains why disguises were not being saved.

```
2020-12-04 03:26:43 [WARN] java.lang.RuntimeException: Cannot modify the bounding box of a disguise which is not TargetType.SHOW_TO_EVERYONE_BUT_THESE_PLAYERS
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.disguisetypes.Disguise.setModifyBoundingBox(Disguise.java:794)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.disguisetypes.MobDisguise.setModifyBoundingBox(MobDisguise.java:149)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.disguisetypes.MobDisguise.setModifyBoundingBox(MobDisguise.java:10)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.disguisetypes.Disguise.clone(Disguise.java:205)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.disguisetypes.TargetedDisguise.clone(TargetedDisguise.java:41)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.disguisetypes.MobDisguise.clone(MobDisguise.java:70)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.disguisetypes.MobDisguise.clone(MobDisguise.java:10)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.utilities.DisguiseUtilities.saveDisguises(DisguiseUtilities.java:577)
2020-12-04 03:26:43 [WARN]      at me.libraryaddict.disguise.utilities.listeners.DisguiseListener.onChunkUnload(DisguiseListener.java:253)
2020-12-04 03:26:43 [WARN]      at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor215.execute(Unknown Source)
2020-12-04 03:26:43 [WARN]      at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
2020-12-04 03:26:43 [WARN]      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
2020-12-04 03:26:43 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
2020-12-04 03:26:43 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.Chunk.unloadCallback(Chunk.java:849)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$null$7(PlayerChunk.java:579)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:589)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.ChunkMapDistance.a(ChunkMapDistance.java:117)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:641)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:739)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
2020-12-04 03:26:43 [WARN]      at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
2020-12-04 03:26:43 [WARN]      at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by libraryaddict** [comment] 2020-12-04 19:11
Fixed in latest build, though technically not a bug.

**Closed by libraryaddict** 2020-12-04 19:11 UTC
