### ISSUE TITLE
Disguising as an entity with GadgetsMenu Premium Crashes ALL Players

### ISSUE THREAD

**Issue by shm3** [libraryaddict/LibsDisguises#696] opened 2023-03-29 17:51 UTC
Hello, I'm running Spigot 1.12.2 with the latest LibsDisguises and GadgetsMenu premium builds. When activating a morph, the plugin spits out the error below and kicks every player online.

**Here is the error received in-game:**
![image](https://user-images.githubusercontent.com/40372194/228625268-69ae7a16-93c3-4595-b7ca-9be5ae8ef290.png)

**Error in Console:**

`java.lang.IllegalArgumentException: You cannot register objects without a watcher object!
[10:39:21 WARN]:        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:401)
[10:39:21 WARN]:        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:452)
[10:39:21 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.createDatawatcher(DisguiseUtilities.java:2857)
[10:39:21 WARN]:        at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.constructSpawnPackets(PacketHandlerSpawn.java:297)
[10:39:21 WARN]:        at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.handle(PacketHandlerSpawn.java:78)
[10:39:21 WARN]:        at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:79)
[10:39:21 WARN]:        at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:56)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[10:39:21 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1142)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:344)
[10:39:21 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:39:21 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:39:21 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:39:21 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[10:39:21 WARN]:        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.addEntityTracker(ReflectionManager.java:1138)
[10:39:21 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.lambda$refreshTrackers$11(DisguiseUtilities.java:1801)
[10:39:21 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[10:39:21 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[10:39:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[10:39:21 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:39:21 ERROR]: java.lang.NullPointerException`

**Comment by libraryaddict** [comment] 2023-03-29 23:06
You say the latest but I thought I fixed this, can you actually post your Lib's Disguises version.

**Comment by libraryaddict** [comment] 2023-03-29 23:07
Wait no, this was a dev build. Not a release build.

Can you try the dev builds?

**Comment by libraryaddict** [comment] 2023-03-29 23:09
Duplicate of #696

**Closed by libraryaddict** 2023-03-29 23:09 UTC

**Comment by shm3** [comment] 2023-03-31 21:10
Here's the list of versions I tried: 
- v10.0.32-SNAPSHOT-b1172 which is the latest dev build as of today...
- I've tried the latest official release on spigot (10.0.32)
- I've tried 10.0.7
- I've tried 10.0.25

Yet I get the same error as above!
