### ISSUE TITLE
Zombie villager crashes the user and anyone around the user

### ISSUE THREAD

**Issue by SirLemonade** [libraryaddict/LibsDisguises#394] opened 2019-09-01 19:01 UTC
https://pastebin.com/CRYAcRdj
Above is the console error message. 
When i select the zombie villager my game crashes and anyone around me also gets kicked. Can not log in without immediatly being disconnected. Can only be fixed by deleting the disguise in saved disguises.

**Comment by libraryaddict** [comment] 2019-09-14 23:08
Dupe of #391

**Closed by libraryaddict** 2019-09-14 23:08 UTC
