### ISSUE TITLE
LibsDisguise crashing all players.

### ISSUE THREAD

**Issue by andrewkm** [libraryaddict/LibsDisguises#338] opened 2019-02-01 11:57 UTC
Using build 258 from jenkins

Finally tracked down an issue happening past few days.
I'm not sure how to reproduce but this plugin is crashing all players randomly once a day. After this crash server stays online but no one is able to connect back in.
Further more I can't even run a stop command on the server, I have to literally crash the instance to bring it back up.

https://pastebin.com/raw/7btw3Jy2

Please look into it.
Removing libsdisguise has fixed the issue and it doesn't happen anymore.

**Comment by andrewkm** [comment] 2019-02-01 13:46
Also should reference this:
https://github.com/SpigotMC/BungeeCord/issues/2597

Since removing libsdisguise I haven’t noticed the above anymore.

**Comment by libraryaddict** [comment] 2019-02-03 00:38
That error shouldn't be related, as the packet is both sent on main thread and ProtocolLib doesn't send packets to closed connections.

It seems related to #320, but likely not the same issue. That issue was caused by another plugin handling packets async.

When you say you cannot use /stop do you mean you cannot access console through the command line? Such as through linux, not using your Minecraft account.

I take it that nothing of interest happened on the MC server itself prior to the crash, and there are no relevant errors. If you cannot access console for this, the latest.log should still contain this information. If you've restarted the server since then, you should still have archives of the old logs.

Are you able to provide a server thread dump? You can send me this on SpigotMC through a private message.

https://www.spigotmc.org/conversations/add?to=libraryaddict

Are you able to track what has changed from when the server was stable, until the issues began?

**Comment by andrewkm** [comment] 2019-02-03 01:39
I will try to respond to this in more depth in 2-3 days.
(Am currently on vacation celebrating [sadly] turning 30 lol).

I can however say, since removing libsdisguise, our entire network has completely stopped booting players/crashing.

**Comment by andrewkm** [comment] 2019-02-03 02:37
Although I cannot go much in depth due to being away from my working environment, I can say, that removing libdisguise has completely stabilized our networks.

Something is definitely up with this plugin.

**Comment by libraryaddict** [comment] 2019-03-05 04:52
Closed as I've been in contact with @andrewkm and no further issues has occurred.

**Closed by libraryaddict** 2019-03-05 04:52 UTC
