### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarkFort** [libraryaddict/LibsDisguises#327] opened 2018-12-20 12:56 UTC
https://hastebin.com/wufosalupa.cs
Latest version LibsDisguises
PaperSpigot 1.13.2

**Comment by Silthus** [comment] 2018-12-20 17:43
This is a duplicate of #324

**Comment by Blueeyestar** [comment] 2018-12-22 15:12
I also have the problem in the latest Spigot version

**CraftBukkit version git-Spigot-573cdf2-dff66df (MC: 1.13.2)** 

[15:49:05] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to LibsDisguises v9.7.1-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:599) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:224) [Citizens.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) [Citizens.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [Citizens.jar:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:306) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.comphenix.protocol.injector.netty.ChannelInjector.findChannelHandler(ChannelInjector.java:843) ~[?:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:745) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:204) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onTeleport(DisguiseListener.java:629) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-573cdf2-dff66df]
	... 16 more

**Comment by libraryaddict** [comment] 2018-12-26 20:52
I had forgotten to ask this, but are you using the latest stable build of ProtocolLib?

http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by TheIntelloBox** [comment] 2018-12-27 13:05
I am yes, but I have the error.

**Comment by Blueeyestar** [comment] 2018-12-28 08:47
I got it running again by taking the latest Citizens 2.0.24-b1605.jar. Now the plugin goes again.

**Comment by TheIntelloBox** [comment] 2018-12-28 13:08
Yeah

**Closed** 2018-12-28 15:00 UTC
