### ISSUE TITLE
Hide and Seek Support

### ISSUE THREAD

**Issue by Cobwebster** [libraryaddict/LibsDisguises#268] opened 2017-12-15 10:02 UTC
Upon using the latest Hide N Seek, Latest libsDisguises and paperSpigot 1.12.2,

https://www.spigotmc.org/resources/hideandseek.9777/

When hitting a disguised hiding player (aka a block in the minigame) it causes a weird visual glitch where the hiding player (a disguised block) just floats upwards making it hard to kill. Not sure if this is of fault of myself, hideandseek or libsdisguise.

The hide and seek dev hasn't logged into spigot for 3 weeks and often takes large breaks in between development.  I was wondering if this was something that could be resolved on your end?

I have a open server if you need to observe it happening (or i can provide a gif)

**Comment by libraryaddict** [comment] 2017-12-15 10:04
I believe what you're talking about is a bug of Lib's Disguises

And is a old bug.

The problem is, I cannot think of a good clean fix for this. So I'll leave this open, but I wouldn't expect to see a fix on my end anytime soon sorry.

**Comment by Cobwebster** [comment] 2017-12-15 10:08
Would you like to come on the server we're testing it on to see it first hand? It doesn't seem to always occur, its like every 5th hit makes it float.

**Comment by Toshka17** [comment] 2018-01-10 12:13
Apparently, I need to switch to IDisguise. It is a pity that I supported the wrong plugin by purchasing a paid version.

**Comment by libraryaddict** [comment] 2018-01-10 12:37
@Toshka17 you happy? Test it and report back.

**Comment by Cobwebster** [comment] 2018-01-10 12:40
Toskha's comment is clearly a bit over the top, LibsDisguises is an amazing plugin which deserves all the sales it gets. I'll test this update later to see if it dose indeed fix the issue.

<3

**Comment by Toshka17** [comment] 2018-01-10 12:47
You fixed it. Thank you.
Yes, I'm happy;)

**Comment by libraryaddict** [comment] 2018-01-10 12:48
Yeah, his comment was definitely over the top. He could've just posted "Hey its been a month since this bug, is there a resolution in sight?"

**Closed by libraryaddict** 2018-01-10 12:48 UTC
