### ISSUE TITLE
Index out of bound

### ISSUE THREAD

**Issue by bobhenl** [libraryaddict/LibsDisguises#768] opened 2024-08-01 20:03 UTC
```yml
[20:01:36 INFO]:
java.lang.ArrayIndexOutOfBoundsException: Index 116 out of bounds for length 3
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readEnum(PacketWrapper.java:1471)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$Modifier.read(ItemAttributeModifiers.java:187)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$ModifierEntry.read(ItemAttributeModifiers.java:113)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1426)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1439)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAttributeModifiers.read(ItemAttributeModifiers.java:50)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:88)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:477)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:496)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.read(WrapperPlayServerEntityEquipment.java:59)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:270)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:175)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:165)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.<init>(WrapperPlayServerEntityEquipment.java:37)
        at LibsDisguises.jar//me.libraryaddict.disguise.utilities.DisguiseUtilities.constructWrapper(DisguiseUtilities.java:2984)
        at LibsDisguises.jar//me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerViewSelfDisguise.onPacketPlaySend(PacketListenerViewSelfDisguise.java:59)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:64)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52)
        at packetevents-spigot-2.4.0.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45)
        at packetevents-spigot-2.4.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
        at packetevents-spigot-2.4.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
        at packetevents-spigot-2.4.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
        at packetevents-spigot-2.4.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
        at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
        at net.minecraft.network.Connection$2.write(Connection.java:771)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at Vulcan-2.9.0.jar//io.github.repooper.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:61)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at TAB v4.1.6.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at GSit-1.9.5.jar//dev.geco.gsit.mcv.v1_21.util.PackageUtil$1.write(PackageUtil.java:91)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$proxyAction$7(NettyChannelInjector.java:566)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by libraryaddict** [comment] 2024-08-01 23:00
Duplicate of https://github.com/retrooper/packetevents/pull/866

**Closed by libraryaddict** 2024-08-01 23:00 UTC
